// web/src/components/MembersColumn.vue
<script setup lang="ts">
/** Members 栏(第二列):AGENTS / HUMANS 分组列表 + 新建 agent。 */

import { ref } from "vue";
import { Plus, GitBranch, Bot, Download } from "lucide-vue-next";
import Avatar from "./Avatar.vue";
import type { AgentStatusInfo, AgentStatusKind, Member } from "../types.js";

const props = defineProps<{
  agents: Member[];
  humans: Member[];
  agentStatus: Record<string, AgentStatusInfo>;
  selectedHandle: string | null;
  onSelectAgent: (handle: string) => void;
  onNewAgent: () => void;
  onImportAgent: () => void;
}>();

const menuOpen = ref(false);
const kindOf = (a: Member): AgentStatusKind => props.agentStatus[a.handle]?.kind ?? (a.online ? "online" : "offline");
const chooseCreate = () => { menuOpen.value = false; props.onNewAgent(); };
const chooseImport = () => { menuOpen.value = false; props.onImportAgent(); };
</script>

<template>
  <div class="col" data-testid="members-column">
    <div class="col-head">Members</div>
    <div class="col-scroll">
      <div class="nav-item" title="Relationship graph (coming soon)">
        <GitBranch :size="16" /><span class="grow">Graph</span>
      </div>

      <div class="sect" :style="{ position: 'relative' }">
        <span>AGENTS</span><span class="count">{{ agents.length }}</span>
        <span class="grow" />
        <button class="sect-add" data-testid="add-agent-btn" title="Add agent" @click="menuOpen = !menuOpen">
          <Plus :size="15" />
        </button>
        <template v-if="menuOpen">
          <div class="menu-backdrop" @click="menuOpen = false" />
          <div class="popmenu" data-testid="add-agent-menu">
            <button class="popmenu-item" data-testid="menu-create-agent" @click="chooseCreate">
              <Bot :size="15" /> Create Agent
            </button>
            <button class="popmenu-item" data-testid="menu-import-agent" @click="chooseImport">
              <Download :size="15" /> Import raft agent
            </button>
          </div>
        </template>
      </div>
      <div v-if="agents.length === 0" class="member-row"><span class="nm" :style="{ color: '#999' }">No agents yet</span></div>
      <div
        v-for="a in agents"
        :key="a.handle"
        data-testid="agent-row"
        :class="`member-row ${a.handle === selectedHandle ? 'active' : ''}`"
        @click="onSelectAgent(a.handle)"
      >
        <Avatar type="agent" :id="a.handle" :size="26" :status="kindOf(a)" :url="a.avatarUrl" />
        <span class="nm">{{ a.displayName }}</span>
        <span v-if="a.description" class="member-sub">{{ a.description }}</span>
        <span :class="`dot ${kindOf(a)}`" :title="agentStatus[a.handle]?.label ?? kindOf(a)" />
      </div>

      <div class="sect">
        <span>HUMANS</span><span class="count">{{ humans.length }}</span>
        <span class="grow" />
        <button class="sect-add" title="Invite member (coming soon)"><Plus :size="15" /></button>
      </div>
      <div v-for="h in humans" :key="h.handle" class="member-row" data-testid="human-row">
        <Avatar type="human" :id="h.handle" :size="26" />
        <span class="nm">{{ h.displayName }}</span>
      </div>
    </div>
  </div>
</template>

// web/src/components/MembersColumn.tsx
/** Members 栏(第二列):AGENTS / HUMANS 分组列表 + 新建 agent。
 *  成员面板:每行 = 头像 + 名称 + 描述/状态点。点击 agent 打开详情。
 *  Graph / 新建 human 暂为占位(后期补充)。 */

import { useState } from "react";
import { Plus, GitBranch, Bot, Download } from "lucide-react";
import { Avatar } from "./Avatar.js";
import type { AgentStatusInfo, Member } from "../types.js";

export function MembersColumn(props: {
  agents: Member[];
  humans: Member[];
  agentStatus: Record<string, AgentStatusInfo>;
  selectedHandle: string | null;
  onSelectAgent: (handle: string) => void;
  onNewAgent: () => void;
  onImportAgent: () => void;
}) {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <div className="col" data-testid="members-column">
      <div className="col-head">Members</div>
      <div className="col-scroll">
        <div className="nav-item" title="Relationship graph (coming soon)">
          <GitBranch size={16} /><span className="grow">Graph</span>
        </div>

        <div className="sect" style={{ position: "relative" }}>
          <span>AGENTS</span><span className="count">{props.agents.length}</span>
          <span className="grow" />
          <button
            className="sect-add" data-testid="add-agent-btn" title="Add agent"
            onClick={() => setMenuOpen((o) => !o)}
          >
            <Plus size={15} />
          </button>
          {menuOpen && (
            <>
              <div className="menu-backdrop" onClick={() => setMenuOpen(false)} />
              <div className="popmenu" data-testid="add-agent-menu">
                <button
                  className="popmenu-item" data-testid="menu-create-agent"
                  onClick={() => { setMenuOpen(false); props.onNewAgent(); }}
                >
                  <Bot size={15} /> Create Agent
                </button>
                <button
                  className="popmenu-item" data-testid="menu-import-agent"
                  onClick={() => { setMenuOpen(false); props.onImportAgent(); }}
                >
                  <Download size={15} /> Import raft agent
                </button>
              </div>
            </>
          )}
        </div>
        {props.agents.length === 0 && (
          <div className="member-row"><span className="nm" style={{ color: "#999" }}>No agents yet</span></div>
        )}
        {props.agents.map((a) => {
          const st = props.agentStatus[a.handle];
          const kind = st?.kind ?? (a.online ? "online" : "offline");
          return (
            <div
              key={a.handle}
              data-testid="agent-row"
              className={`member-row ${a.handle === props.selectedHandle ? "active" : ""}`}
              onClick={() => props.onSelectAgent(a.handle)}
            >
              <Avatar type="agent" id={a.handle} size={26} status={kind} url={a.avatarUrl} />
              <span className="nm">{a.displayName}</span>
              {a.description && <span className="member-sub">{a.description}</span>}
              <span className={`dot ${kind}`} title={st?.label ?? kind} />
            </div>
          );
        })}

        <div className="sect">
          <span>HUMANS</span><span className="count">{props.humans.length}</span>
          <span className="grow" />
          <button className="sect-add" title="Invite member (coming soon)"><Plus size={15} /></button>
        </div>
        {props.humans.map((h) => (
          <div key={h.handle} className="member-row" data-testid="human-row">
            <Avatar type="human" id={h.handle} size={26} />
            <span className="nm">{h.displayName}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
