// web/src/components/ModelPicker.tsx
/** Model selector: preset dropdown + "Custom…" → free text input.
 *  When an agent runs against a custom base URL the model id may differ, so Custom
 *  lets users type any model id. value = the raw model string ("" = default to daemon). */

import { useState } from "react";

const MODEL_PRESETS: ReadonlyArray<readonly [string, string]> = [
  ["", "Default (daemon)"],
  ["claude-opus-4-8", "Claude Opus 4.8"],
  ["claude-sonnet-4-6", "Claude Sonnet 4.6"],
  ["claude-haiku-4-5", "Claude Haiku 4.5"],
  ["claude-fable-5", "Claude Fable 5"],
];

const CUSTOM = "__custom__";

export function ModelPicker(props: {
  value: string;
  onChange: (v: string) => void;
  controlClass?: string;
  testid?: string;
}) {
  const isPreset = MODEL_PRESETS.some(([v]) => v === props.value);
  const [custom, setCustom] = useState(props.value !== "" && !isPreset);

  return (
    <>
      <select
        className={props.controlClass}
        data-testid={props.testid}
        value={custom ? CUSTOM : props.value}
        onChange={(e) => {
          if (e.target.value === CUSTOM) { setCustom(true); props.onChange(""); }
          else { setCustom(false); props.onChange(e.target.value); }
        }}
      >
        {MODEL_PRESETS.map(([v, label]) => <option key={v || "default"} value={v}>{label}</option>)}
        <option value={CUSTOM}>Custom…</option>
      </select>
      {custom && (
        <input
          className={props.controlClass}
          data-testid={props.testid ? `${props.testid}-custom` : undefined}
          placeholder="Custom model id, e.g. gpt-5.5"
          value={props.value}
          onChange={(e) => props.onChange(e.target.value)}
          style={{ marginTop: 8 }}
        />
      )}
    </>
  );
}

// web/src/components/ModelPicker.vue
<script setup lang="ts">
/** Model 选择器:预设下拉 + "Custom…" → 自由文本输入。
 *  value = 原始 model 字符串(""=交给 daemon 默认)。 */

import { ref } from "vue";

const props = defineProps<{
  value: string;
  onChange: (v: string) => void;
  controlClass?: string;
  testid?: string;
}>();

const MODEL_PRESETS: ReadonlyArray<readonly [string, string]> = [
  ["", "Default (daemon)"],
  ["claude-opus-4-8", "Claude Opus 4.8"],
  ["claude-sonnet-4-6", "Claude Sonnet 4.6"],
  ["claude-haiku-4-5", "Claude Haiku 4.5"],
  ["claude-fable-5", "Claude Fable 5"],
];
const CUSTOM = "__custom__";

const isPreset = MODEL_PRESETS.some(([v]) => v === props.value);
const custom = ref(props.value !== "" && !isPreset);
const customTestid = props.testid ? `${props.testid}-custom` : undefined;

function onSelect(e: Event) {
  const val = (e.target as HTMLSelectElement).value;
  if (val === CUSTOM) { custom.value = true; props.onChange(""); }
  else { custom.value = false; props.onChange(val); }
}
function onCustomInput(e: Event) {
  props.onChange((e.target as HTMLInputElement).value);
}
</script>

<template>
  <select :class="controlClass" :data-testid="testid" :value="custom ? CUSTOM : value" @change="onSelect">
    <option v-for="[v, label] in MODEL_PRESETS" :key="v || 'default'" :value="v">{{ label }}</option>
    <option :value="CUSTOM">Custom…</option>
  </select>
  <input
    v-if="custom"
    :class="controlClass"
    :data-testid="customTestid"
    placeholder="Custom model id, e.g. gpt-5.5"
    :value="value"
    :style="{ marginTop: '8px' }"
    @input="onCustomInput"
  />
</template>
