// web/src/components/SearchView.vue
<script setup lang="ts">
/** 全局搜索:输入关键词 → 后端 message search → 结果可点跳到频道。 */

import { ref } from "vue";
import type { AgentStatusInfo, Channel, Message } from "../types.js";
import Avatar from "./Avatar.vue";

const props = defineProps<{
  channels: Channel[];
  agentStatus: Record<string, AgentStatusInfo>;
  onSearch: (q: string) => Promise<Message[]>;
  onJump: (channelId: string) => void;
}>();

const q = ref("");
const results = ref<Message[] | null>(null);
const busy = ref(false);

async function run() {
  const t = q.value.trim();
  if (!t) return;
  busy.value = true;
  try { results.value = await props.onSearch(t); } finally { busy.value = false; }
}
const chanName = (id: string) => {
  const c = props.channels.find((x) => x.id === id);
  return c ? (c.name ?? c.slug) : id.slice(0, 8);
};
</script>

<template>
  <div class="chat" data-testid="search-view">
    <div class="task-toolbar">
      <input
        class="nb-btn"
        :style="{ fontWeight: '400', flex: '1' }"
        data-testid="search-input"
        autofocus
        placeholder="Search messages…"
        v-model="q"
        @keydown.enter="run"
      />
      <button class="nb-btn primary" data-testid="search-btn" :disabled="busy || !q.trim()" @click="run">Search</button>
    </div>
    <div class="msgs">
      <div v-if="results === null" class="placeholder"><div class="fake">Type a keyword to search messages visible in this workspace</div></div>
      <div v-if="results !== null && results.length === 0" class="placeholder"><div>No matches</div></div>
      <div
        v-for="m in (results ?? [])"
        :key="m.id"
        :class="`msg ${m.type}`"
        data-testid="search-result"
        :style="{ cursor: 'pointer' }"
        @click="onJump(m.channelId)"
      >
        <Avatar :type="m.type" :id="m.sender.id" :status="m.type === 'agent' ? agentStatus[m.sender.id]?.kind : undefined" />
        <div class="body">
          <div class="line1">
            <span class="who">{{ m.sender.id }}</span>
            <span class="meta mono">#{{ chanName(m.channelId) }} · #{{ m.seq }}</span>
          </div>
          <div class="content">{{ m.content }}</div>
        </div>
      </div>
    </div>
  </div>
</template>

// web/src/components/SearchView.tsx
/** 全局搜索:输入关键词 → 后端 message search(pg_trgm 子串)→ 结果可点跳到频道。 */

import { useState } from "react";
import type { AgentStatusInfo, Channel, Message } from "../types.js";
import { Avatar } from "./Avatar.js";

export function SearchView(props: {
  channels: Channel[];
  agentStatus: Record<string, AgentStatusInfo>;
  onSearch: (q: string) => Promise<Message[]>;
  onJump: (channelId: string) => void;
}) {
  const [q, setQ] = useState("");
  const [results, setResults] = useState<Message[] | null>(null);
  const [busy, setBusy] = useState(false);

  const run = async () => {
    const t = q.trim();
    if (!t) return;
    setBusy(true);
    try { setResults(await props.onSearch(t)); } finally { setBusy(false); }
  };
  const chanName = (id: string) => {
    const c = props.channels.find((x) => x.id === id);
    return c ? (c.name ?? c.slug) : id.slice(0, 8);
  };

  return (
    <div className="chat" data-testid="search-view">
      <div className="task-toolbar">
        <input
          className="nb-btn" style={{ fontWeight: 400, flex: 1 }}
          data-testid="search-input" autoFocus placeholder="Search messages…"
          value={q} onChange={(e) => setQ(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && void run()}
        />
        <button className="nb-btn primary" data-testid="search-btn" disabled={busy || !q.trim()} onClick={run}>Search</button>
      </div>
      <div className="msgs">
        {results === null && <div className="placeholder"><div className="fake">Type a keyword to search messages visible in this workspace</div></div>}
        {results !== null && results.length === 0 && <div className="placeholder"><div>No matches</div></div>}
        {results?.map((m) => (
          <div key={m.id} className={`msg ${m.type}`} data-testid="search-result" onClick={() => props.onJump(m.channelId)} style={{ cursor: "pointer" }}>
            <Avatar type={m.type} id={m.sender.id} status={m.type === "agent" ? props.agentStatus[m.sender.id]?.kind : undefined} />
            <div className="body">
              <div className="line1">
                <span className="who">{m.sender.id}</span>
                <span className="meta mono">#{chanName(m.channelId)} · #{m.seq}</span>
              </div>
              <div className="content">{m.content}</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
