// web/src/components/SettingsDialog.vue
<script setup lang="ts">
/** Settings dialog —— 工作区信息、当前身份、连接状态、登出。 */

import { ref, onMounted } from "vue";
import { Check } from "lucide-vue-next";
import Avatar from "./Avatar.vue";
import { api } from "../api.js";
import type { Me } from "../types.js";

defineProps<{
  connected: boolean;
  onClose: () => void;
  onLogout: () => void;
}>();

const me = ref<Me | null>(null);
const error = ref<string | null>(null);

onMounted(() => {
  api.me().then((v) => { me.value = v; }).catch((e) => { error.value = (e as Error).message; });
});
</script>

<template>
  <div class="modal-overlay" data-testid="settings-dialog" @click="onClose">
    <div class="modal" @click.stop>
      <div class="modal-head">Settings</div>
      <div class="modal-body">
        <div v-if="error" class="gate-error">{{ error }}</div>
        <div v-if="!me && !error" class="fake">Loading…</div>
        <template v-if="me">
          <label>WORKSPACE</label>
          <div class="ws-switcher">
            <div class="ws-entry active" data-testid="ws-entry">
              <div class="ws-badge">{{ me.workspace.name.slice(0, 1).toUpperCase() }}</div>
              <div class="ws-meta">
                <div class="ws-name">{{ me.workspace.name }}</div>
                <div class="ws-slug">/{{ me.workspace.slug }}</div>
              </div>
              <Check :size="16" />
            </div>
          </div>
          <div class="field-hint">Switching between workspaces requires multi-workspace membership (coming soon).</div>

          <label :style="{ marginTop: '14px' }">SIGNED IN AS</label>
          <div class="me-row" data-testid="me-row">
            <Avatar :type="me.actor.type === 'agent' ? 'agent' : 'human'" :id="me.actor.id" :size="32" />
            <div class="ws-meta">
              <div class="ws-name">{{ me.displayName }}</div>
              <div class="ws-slug">@{{ me.actor.id }} · {{ me.tier }}</div>
            </div>
          </div>

          <label :style="{ marginTop: '14px' }">CONNECTION</label>
          <div class="conn-line">
            <span :class="`dot ${connected ? 'online' : 'offline'}`" />
            {{ connected ? "Connected (realtime)" : "Disconnected" }}
          </div>
        </template>
      </div>
      <div class="modal-foot">
        <button class="nb-btn" @click="onClose">Close</button>
        <button class="nb-btn primary" data-testid="settings-signout" @click="onLogout">Sign out</button>
      </div>
    </div>
  </div>
</template>

// web/src/components/SettingsDialog.tsx
/** Settings dialog — workspace info, your identity, connection, sign out.
 *  Workspace switcher: our accounts map 1:1 to a workspace, so the current workspace is shown
 *  as the only (active) entry; true switching needs multi-workspace membership (future). */

import { useEffect, useState } from "react";
import { Check } from "lucide-react";
import { Avatar } from "./Avatar.js";
import { api } from "../api.js";
import type { Me } from "../types.js";

export function SettingsDialog(props: {
  connected: boolean;
  onClose: () => void;
  onLogout: () => void;
}) {
  const [me, setMe] = useState<Me | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api.me().then(setMe).catch((e) => setError((e as Error).message));
  }, []);

  return (
    <div className="modal-overlay" data-testid="settings-dialog" onClick={props.onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-head">Settings</div>
        <div className="modal-body">
          {error && <div className="gate-error">{error}</div>}
          {!me && !error && <div className="fake">Loading…</div>}
          {me && (
            <>
              <label>WORKSPACE</label>
              <div className="ws-switcher">
                <div className="ws-entry active" data-testid="ws-entry">
                  <div className="ws-badge">{me.workspace.name.slice(0, 1).toUpperCase()}</div>
                  <div className="ws-meta">
                    <div className="ws-name">{me.workspace.name}</div>
                    <div className="ws-slug">/{me.workspace.slug}</div>
                  </div>
                  <Check size={16} />
                </div>
              </div>
              <div className="field-hint">Switching between workspaces requires multi-workspace membership (coming soon).</div>

              <label style={{ marginTop: 14 }}>SIGNED IN AS</label>
              <div className="me-row" data-testid="me-row">
                <Avatar type={me.actor.type === "agent" ? "agent" : "human"} id={me.actor.id} size={32} />
                <div className="ws-meta">
                  <div className="ws-name">{me.displayName}</div>
                  <div className="ws-slug">@{me.actor.id} · {me.tier}</div>
                </div>
              </div>

              <label style={{ marginTop: 14 }}>CONNECTION</label>
              <div className="conn-line">
                <span className={`dot ${props.connected ? "online" : "offline"}`} />
                {props.connected ? "Connected (realtime)" : "Disconnected"}
              </div>
            </>
          )}
        </div>
        <div className="modal-foot">
          <button className="nb-btn" onClick={props.onClose}>Close</button>
          <button className="nb-btn primary" data-testid="settings-signout" onClick={props.onLogout}>Sign out</button>
        </div>
      </div>
    </div>
  );
}
