// web/src/components/ThreadPanel.vue
<script setup lang="ts">
/** Thread 面板(右侧第 4 栏):父消息 + 回复串 + 线程内发送。 */

import { ref, watch } from "vue";
import { Paperclip } from "lucide-vue-next";
import type { AgentStatusInfo, Channel, Member, Message } from "../types.js";
import Avatar from "./Avatar.vue";
import MentionTextarea from "./MentionTextarea.vue";
import MessageText from "./MessageText.vue";
import AttachmentList from "./AttachmentList.vue";
import PendingFiles from "./PendingFiles.vue";
import { imagesFromClipboard } from "../lib/clipboard.js";

const props = defineProps<{
  channelName: string;
  parent: Message;
  replies: Message[];
  channels: Channel[];
  memberHandles: Set<string>;
  mentionMembers: Member[];
  agentStatus: Record<string, AgentStatusInfo>;
  onChannel: (id: string) => void;
  onTask: () => void;
  onReply: (content: string) => Promise<void>;
  onReplyFiles: (content: string, files: File[]) => Promise<void>;
  onClose: () => void;
}>();

const endRef = ref<HTMLDivElement | null>(null);
const text = ref("");
const busy = ref(false);
const files = ref<File[]>([]);
const fileInputRef = ref<HTMLInputElement | null>(null);

watch(() => props.replies.length, () => { endRef.value?.scrollIntoView({ behavior: "smooth" }); }, { flush: "post", immediate: true });

const submit = async () => {
  const t = text.value.trim();
  if ((!t && files.value.length === 0) || busy.value) return;
  busy.value = true;
  try {
    if (files.value.length) await props.onReplyFiles(t, files.value);
    else await props.onReply(t);
    text.value = ""; files.value = [];
  } finally { busy.value = false; }
};

const removeFile = (i: number) => { files.value = files.value.filter((_, j) => j !== i); };
const onPaste = (e: ClipboardEvent) => {
  const imgs = imagesFromClipboard(e);
  if (imgs.length) { e.preventDefault(); files.value = [...files.value, ...imgs]; }
};
const onFileChange = (e: Event) => {
  const input = e.target as HTMLInputElement;
  files.value = [...files.value, ...Array.from(input.files ?? [])];
  if (fileInputRef.value) fileInputRef.value.value = "";
};
</script>

<template>
  <aside class="thread" data-testid="thread-panel">
    <div class="thread-head">
      <div><b>Thread</b> <span class="meta">— #{{ channelName }}</span></div>
      <button class="nb-btn" data-testid="thread-close" @click="onClose">×</button>
    </div>
    <div class="thread-body">
      <div class="thread-parent">
        <div :class="`msg ${parent.type}`" data-testid="thread-msg">
          <Avatar :type="parent.type" :id="parent.sender.id" :size="28" :status="parent.type === 'agent' ? agentStatus[parent.sender.id]?.kind : undefined" />
          <div class="body">
            <div class="line1"><span class="who">{{ parent.sender.id }}</span><span class="meta mono">#{{ parent.seq }}</span></div>
            <div class="content"><MessageText :content="parent.content" :channels="channels" :memberHandles="memberHandles" :onChannel="onChannel" :onTask="onTask" /></div>
            <AttachmentList :attachments="parent.attachments ?? []" />
          </div>
        </div>
      </div>
      <div class="thread-divider">{{ replies.length }} {{ replies.length === 1 ? "reply" : "replies" }}</div>
      <div v-if="replies.length === 0" class="fake" :style="{ padding: '12px' }">No replies yet — start the discussion below</div>
      <div v-for="m in replies" :key="m.id" :class="`msg ${m.type}`" data-testid="thread-msg">
        <Avatar :type="m.type" :id="m.sender.id" :size="28" :status="m.type === 'agent' ? agentStatus[m.sender.id]?.kind : undefined" />
        <div class="body">
          <div class="line1"><span class="who">{{ m.sender.id }}</span><span class="meta mono">#{{ m.seq }}</span></div>
          <div class="content"><MessageText :content="m.content" :channels="channels" :memberHandles="memberHandles" :onChannel="onChannel" :onTask="onTask" /></div>
          <AttachmentList :attachments="m.attachments ?? []" />
        </div>
      </div>
      <div ref="endRef" />
    </div>
    <div class="composer composer-col">
      <PendingFiles :files="files" :onRemove="removeFile" />
      <MentionTextarea
        test-id="thread-input"
        placeholder="Reply to thread… (Enter to send)"
        v-model="text"
        :members="mentionMembers"
        :disabled="busy"
        @paste="onPaste"
        @enter="submit"
      />
      <div class="composer-foot">
        <input
          ref="fileInputRef" type="file" multiple data-testid="thread-file-input" :style="{ display: 'none' }"
          @change="onFileChange"
        />
        <button class="nb-btn" data-testid="thread-attach-btn" title="Attach files" :disabled="busy" @click="fileInputRef?.click()">
          <Paperclip :size="14" />
        </button>
        <span class="grow" />
        <button class="nb-btn primary" data-testid="thread-send" :disabled="busy || (!text.trim() && files.length === 0)" @click="submit">Send</button>
      </div>
    </div>
  </aside>
</template>

// web/src/components/ThreadPanel.tsx
/** Thread 面板(右侧第 4 栏):父消息 + 回复串 + 线程内发送。 */

import { useEffect, useRef, useState } from "react";
import { Paperclip } from "lucide-react";
import type { AgentStatusInfo, Channel, Member, Message } from "../types.js";
import { Avatar } from "./Avatar.js";
import { MentionTextarea } from "./MentionTextarea.js";
import { MessageText } from "./MessageText.js";
import { AttachmentList } from "./AttachmentList.js";
import { PendingFiles, imagesFromClipboard } from "./PendingFiles.js";

export function ThreadPanel(props: {
  channelName: string;
  parent: Message;
  replies: Message[];
  channels: Channel[];
  memberHandles: Set<string>;
  members: Member[];
  agentStatus: Record<string, AgentStatusInfo>;
  onChannel: (id: string) => void;
  onTask: () => void;
  onReply: (content: string) => Promise<void>;
  onReplyFiles: (content: string, files: File[]) => Promise<void>;
  onClose: () => void;
}) {
  const endRef = useRef<HTMLDivElement>(null);
  const [text, setText] = useState("");
  const [busy, setBusy] = useState(false);
  const [files, setFiles] = useState<File[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [props.replies.length]);

  const submit = async () => {
    const t = text.trim();
    if ((!t && files.length === 0) || busy) return;
    setBusy(true);
    try {
      if (files.length) await props.onReplyFiles(t, files);
      else await props.onReply(t);
      setText(""); setFiles([]);
    } finally { setBusy(false); }
  };

  const Row = (m: Message) => (
    <div key={m.id} className={`msg ${m.type}`} data-testid="thread-msg">
      <Avatar type={m.type} id={m.sender.id} size={28} status={m.type === "agent" ? props.agentStatus[m.sender.id]?.kind : undefined} />
      <div className="body">
        <div className="line1"><span className="who">{m.sender.id}</span><span className="meta mono">#{m.seq}</span></div>
        <div className="content"><MessageText content={m.content} channels={props.channels} memberHandles={props.memberHandles} onChannel={props.onChannel} onTask={props.onTask} /></div>
        <AttachmentList attachments={m.attachments ?? []} />
      </div>
    </div>
  );

  return (
    <aside className="thread" data-testid="thread-panel">
      <div className="thread-head">
        <div><b>Thread</b> <span className="meta">— #{props.channelName}</span></div>
        <button className="nb-btn" data-testid="thread-close" onClick={props.onClose}>×</button>
      </div>
      <div className="thread-body">
        <div className="thread-parent">{Row(props.parent)}</div>
        <div className="thread-divider">{props.replies.length} {props.replies.length === 1 ? "reply" : "replies"}</div>
        {props.replies.length === 0 && <div className="fake" style={{ padding: 12 }}>No replies yet — start the discussion below</div>}
        {props.replies.map(Row)}
        <div ref={endRef} />
      </div>
      <div className="composer composer-col">
        <PendingFiles files={files} onRemove={(i) => setFiles((prev) => prev.filter((_, j) => j !== i))} />
        <MentionTextarea
          testId="thread-input"
          placeholder="Reply to thread… (Enter to send)"
          value={text}
          disabled={busy}
          members={props.members}
          onChange={setText}
          onPaste={(e) => { const imgs = imagesFromClipboard(e); if (imgs.length) { e.preventDefault(); setFiles((prev) => [...prev, ...imgs]); } }}
          onEnter={() => void submit()}
        />
        <div className="composer-foot">
          <input
            ref={fileInputRef} type="file" multiple data-testid="thread-file-input" style={{ display: "none" }}
            onChange={(e) => { setFiles((prev) => [...prev, ...Array.from(e.target.files ?? [])]); if (fileInputRef.current) fileInputRef.current.value = ""; }}
          />
          <button className="nb-btn" data-testid="thread-attach-btn" title="Attach files" disabled={busy} onClick={() => fileInputRef.current?.click()}>
            <Paperclip size={14} />
          </button>
          <span className="grow" />
          <button className="nb-btn primary" data-testid="thread-send" disabled={busy || (!text.trim() && files.length === 0)} onClick={submit}>Send</button>
        </div>
      </div>
    </aside>
  );
}
