// web-vue/src/components/TokenGate.vue
<script setup lang="ts">
/** 登录门:邮箱密码登录,或注册新工作区 → 换取 sk_user_* 令牌。 */

import { ref, computed } from "vue";
import { Users } from "lucide-vue-next";
import { login, register } from "../api.js";

const props = defineProps<{ onConnect: (token: string) => void }>();

const mode = ref<"signin" | "register">("signin");
const email = ref("");
const password = ref("");
const workspaceName = ref("");
const displayName = ref("");
const error = ref<string | null>(null);
const busy = ref(false);

const canSubmit = computed(() => mode.value === "signin"
  ? Boolean(email.value.trim() && password.value)
  : Boolean(email.value.trim() && password.value.length >= 8 && workspaceName.value.trim()));

const go = async () => {
  if (!canSubmit.value || busy.value) return;
  busy.value = true; error.value = null;
  try {
    const r = mode.value === "signin"
      ? await login(email.value.trim(), password.value)
      : await register({ email: email.value.trim(), password: password.value, workspaceName: workspaceName.value.trim(), ...(displayName.value.trim() ? { displayName: displayName.value.trim() } : {}) });
    props.onConnect(r.token);
  } catch (e) {
    error.value = (e as Error).message;
  } finally {
    busy.value = false;
  }
};

const toggleMode = () => { mode.value = mode.value === "signin" ? "register" : "signin"; error.value = null; };
</script>

<template>
  <div class="gate" data-testid="login-gate">
    <div class="gate-top"><Users :size="22" :stroke-width="2.4" /> CREW</div>
    <div class="gate-card">
      <h1>{{ mode === "signin" ? "Sign In" : "Create Workspace" }}</h1>
      <p>Where humans and AI agents build together</p>

      <template v-if="mode === 'register'">
        <label>Workspace name</label>
        <input data-testid="ws-name-input" placeholder="Acme Crew" v-model="workspaceName" @keydown.enter="go" />
        <label>Your name <span class="hint">(optional)</span></label>
        <input data-testid="display-name-input" placeholder="Alice" v-model="displayName" @keydown.enter="go" />
      </template>

      <label>Email</label>
      <input data-testid="email-input" type="email" placeholder="you@example.com" v-model="email" @keydown.enter="go" />
      <label>Password <span v-if="mode === 'register'" class="hint">(min 8 chars)</span></label>
      <input data-testid="password-input" type="password" placeholder="••••••••" v-model="password" @keydown.enter="go" />
      <div v-if="error" class="gate-error" data-testid="login-error">{{ error }}</div>
      <button class="nb-btn primary" data-testid="signin-btn" :disabled="busy || !canSubmit" @click="go">
        {{ busy ? "Working…" : mode === "signin" ? "Sign In" : "Create Workspace" }}
      </button>
      <button class="gate-toggle" data-testid="toggle-mode" type="button" @click="toggleMode">
        {{ mode === "signin" ? "New here? Create a workspace" : "Already have an account? Sign in" }}
      </button>
    </div>
  </div>
</template>

// web/src/components/TokenGate.tsx
import { useState } from "react";
import { Users } from "lucide-react";
import { login, register } from "../api.js";

/** 登录门:邮箱密码登录,或注册新工作区 → 换取 sk_user_* 令牌。 */
export function TokenGate(props: { onConnect: (token: string) => void }) {
  const [mode, setMode] = useState<"signin" | "register">("signin");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [workspaceName, setWorkspaceName] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const canSubmit = mode === "signin"
    ? Boolean(email.trim() && password)
    : Boolean(email.trim() && password.length >= 8 && workspaceName.trim());

  const go = async () => {
    if (!canSubmit || busy) return;
    setBusy(true); setError(null);
    try {
      const r = mode === "signin"
        ? await login(email.trim(), password)
        : await register({ email: email.trim(), password, workspaceName: workspaceName.trim(), ...(displayName.trim() ? { displayName: displayName.trim() } : {}) });
      props.onConnect(r.token);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="gate" data-testid="login-gate">
      <div className="gate-top"><Users size={22} strokeWidth={2.4} /> CREW</div>
      <div className="gate-card">
        <h1>{mode === "signin" ? "Sign In" : "Create Workspace"}</h1>
        <p>Where humans and AI agents build together</p>

        {mode === "register" && (
          <>
            <label>Workspace name</label>
            <input
              data-testid="ws-name-input" placeholder="Acme Crew"
              value={workspaceName} onChange={(e) => setWorkspaceName(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && void go()}
            />
            <label>Your name <span className="hint">(optional)</span></label>
            <input
              data-testid="display-name-input" placeholder="Alice"
              value={displayName} onChange={(e) => setDisplayName(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && void go()}
            />
          </>
        )}

        <label>Email</label>
        <input
          data-testid="email-input" type="email" placeholder="you@example.com"
          value={email} onChange={(e) => setEmail(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && void go()}
        />
        <label>Password {mode === "register" && <span className="hint">(min 8 chars)</span>}</label>
        <input
          data-testid="password-input" type="password" placeholder="••••••••"
          value={password} onChange={(e) => setPassword(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && void go()}
        />
        {error && <div className="gate-error" data-testid="login-error">{error}</div>}
        <button className="nb-btn primary" data-testid="signin-btn" disabled={busy || !canSubmit} onClick={go}>
          {busy ? "Working…" : mode === "signin" ? "Sign In" : "Create Workspace"}
        </button>
        <button
          className="gate-toggle" data-testid="toggle-mode" type="button"
          onClick={() => { setMode((m) => (m === "signin" ? "register" : "signin")); setError(null); }}
        >
          {mode === "signin" ? "New here? Create a workspace" : "Already have an account? Sign in"}
        </button>
      </div>
    </div>
  );
}
